apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-buy-bot-server
spec:
  hosts:
    - aks-buy-devint.hospitalityrevolution.com
    - aks-buy-devint.rguest.internal
  gateways:
    - buy-gateway
  http:
    - match:
        - uri:
            prefix: /bot-server/webhooks/socketio
        - headers:
            upgrade:
              exact: websocket
      rewrite:
        uri: /webhooks/socketio
      route:
        - destination:
            host: bot-server.agys-buy.svc.cluster.local
            port:
              number: 5005
      timeout: 1000s
    - match:
        - uri:
            exact: /bot-server
        - uri:
            prefix: /bot-server/
      rewrite:
        uri: /
      route:
        - destination:
            host: bot-server.agys-buy.svc.cluster.local
            port:
              number: 5005
